services:
  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: frontend/
      dockerfile: Dev.Dockerfile
    expose:
      - "80"
    volumes:
      - ./frontend:/vue_app
    depends_on:
      - backend
    networks:
      - proxy
      
  backend:
    container_name: backend
    hostname: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    expose:
      - "8081"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - database
      - proxy

  proxy:
    container_name: proxy
    build:
      context: proxy/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - proxy

  db:
    container_name: database
    hostname: mongodb
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - mongo-data:/data/db
    networks:
      - database

volumes:
  mongo-data:

networks:
  database:
  proxy: