services:
  app:
    container_name: hello_world_app
    build:
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - database

  mongodb:
    container_name: hello_world_mongodb
    hostname: mongodb
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - database

volumes:
  mongo-data:

networks:
  database: